update pipelines

diff --git a/pipes/halffilter_MB b/pipes/halffilter_MB
--- a/pipes/halffilter_MB
+++ b/pipes/halffilter_MB
@@ -1,44 +1,22 @@
 #!/usr/bin/bash
+PIPE_FOR="SM"
+PIPE_DESC80="MMY3(+4?) -scrub +wave +hpfilter.099 +reg:m,wm,csf,alldervs"
 PIPE_DESC="
 This pipeline processes rest data for Scott's MEG subjects
 using Multiband Data (using fieldmaps and ref&func from hdr/img )
 scrubbing no
 wavlet    yes
-filter    highpass only (.008)
+filter    filter anyting lower than .009 (give 3dBandpass 999 > Nysquist => highpass only)
+regs      6motion,wm,csf,d6motion,dwm,dcsf 
 "
-PIPE_DEPENDS=("MHT1_2mm" "MHFM" )
+PIPE_DEPENDS=("MHT1_2mm" "cpFM" )
 PIPE_VERSION="20151215"
 FINALOUT=( ".preprocessfunctional_complete" )
 
-function find_t1final {
- id="$1"
- wantonlyoneid $id || return 1
-
- # need t1 should be done b/c of depends
- mpragedir=$PPSUBJSDIR/../MHT1_2mm/$id
- [ ! -d $mpragedir ] && warn "# cannot find $mpragedir" && return 1
- 
- # should have bet and warp outputs
- bet=$mpragedir/mprage_bet.nii.gz
- warp=$mpragedir/mprage_warpcoef.nii.gz
- [ ! -r "$bet"  ] && warn "# cannot read bet '$bet'" && return 1
- [ ! -r "$warp" ] && warn "# cannot read warp '$warp'" && return 1
- echo "$bet $warp"
-}
-
-# return mag/MR* and phase/MR*
-functional find_fm {
- id="$1"
- wantonlyoneid $id || return 1
- fmdir=$PPSUBJSDIR/../MHFM/$id/
- magphase=""
- for fm in mag phase; do
-  d=$fmdir/$fm
-  [ ! -r $d ] && warn "# missing fm dir $d for $id" && return 1
-  magphase="$magphase $d/MR\*"
- done
-
- echo $magphase
+function check_complete {
+ wantonlyoneid $@ || return 1
+ has_finalout  $1 || return 1
+ return 0
 }
 
 function run_pipeline {
@@ -53,33 +31,36 @@ function run_pipeline {
  t2=$(subj_t2 $id)
  ref=$(subj_ref $id)
  read mag phase < <(find_fm $id)
- read bet warp < <(find_t1final $id)
+ read bet warp  < <(find_t1final $id)
  for v in t2 ref mag phase bet warp; do
    [ -z "${!v}" ] && warn "# cannot find $v for $id" && return 1
  done
 
  # create nii.gz from analize fmt (img hdr)
- [ ! -r functional.nii.gz ]     && 3dcopy $t2 functional.nii.gz
+ [ ! -r functional.nii.gz ]     && 3dcopy $t2  functional.nii.gz
  [ ! -r functional_ref.nii.gz ] && 3dcopy $ref functional_ref.nii.gz
+ [ ! -r functional.nii.gz -o ! -r functional_ref.nii.gz ] && 
+    warn "# failed to copy analyse ($t2 and $ref) into $(pwd)" && return 1
 
-
- if [ ! -r 'functional.nii.gz' ]; then
-   [ $(find . -maxdepth 1 -type l -iname 'MR*' | wc -l) -gt 0 ] && rm MR*
-   ! ln -s $t2dir/MR* ./ && warn "cannot link $t2dir/MR* files" && return 1
- fi
 
  preprocessFunctional -4d 'functional.nii.gz' \
-   -tr $TR -slice_acquisition $SLI
+   -func_refimg functional_ref.nii.gz \
+   -tr $FUNCTR -slice_acquisition $FUNCSLICEACQ \
    -mprage_bet $bet -warpcoef $warp \
    -4d_slice_motion -wavelet_despike  \
    -rescaling_method 10000_globalmedian \
    -template_brain MNI_3mm    \
-   -nuisance_compute 6motion,rx,ry,rz,tx,ty,tz,wm,csf,gs,d6motion,drx,dry,drz,dtx,dty,dtz,dwm,dcsf,dgs \
-   -ref functional_ref.nii.gz \
-   -fm_phase $phase  -fm_magnitude $mag
+   -fm_cfg clock \
+   -fm_phase "$phase"  -fm_magnitude "$mag" \
+   -nuisance_regression 6motion,wm,csf,d6motion,dwm,dcsf \
+   -bandpass_filter 0.009 9999 \
    -no_hp #default is 80, maybe want 125s (.008)
 
    # these options are taken from the dicoms, hopefully
    #-tr 1.5 -slice_acquisition seqasc  \
+
+ check_complete $id || return 1
+
+ return 0
 }
 
