can use ge or siemens fieldmap; update waitforjobs

diff --git a/pipes/ppDistortion b/pipes/ppDistortion
--- a/pipes/ppDistortion
+++ b/pipes/ppDistortion
@@ -6,8 +6,9 @@ with preprocessDistortion.
 also see MHFM
 "
 PIPE_DEPENDS=""
-PIPE_VERSION="20171114"
-FINALOUT=(".preprocessDistortion_complete" "unwarp/FM_UD_fmap_mag.nii.gz"  "unwarp/FM_UD_fmap.nii.gz")
+#PIPE_VERSION="20171114"
+PIPE_VERSION="20191111" # add fmtype - default to siemens; allow for ncanda pipeline
+FINALOUT=(".preprocessDistortion_complete" "unwarp/FM_UD_fmap_mag.nii.gz"  "unwarp/FM_UD_fmap.nii.gz" "unwarp/fm.cfg")
 
 function check_complete {
  wantonlyoneid $@ || return 1
@@ -22,15 +23,37 @@ function run_pipeline {
  wantonlyoneid $id || return 1
  [ ! -d "$id" ] && mkdir $id
  cd $id
+ # use function if we have it [currently only ncanda source - 20191111]
+ declare -f fm_cfg >/dev/null && FM_CFG=$(fm_cfg "$id")
+ # otherwise should be set globally
  [ -z $FM_CFG ] && warn "pipeline requires FM_CFG. Not provided by source!" && return 1
 
- # find the t1dir with MRs in it
- read mrmag mrphase < <(subj_fm $id)
- [ -z "$mrmag" -o -z "$mrphase" ] && warn "could not find fm mag and phase for $id: source pipeline and source; 'subj_fm $id'" && return 1
- [ ! -d "$mrmag" ] && warn "bad mrphase dir $mrmag" && return 1
- [ ! -d "$mrphase" ] && warn "bad mrphase dir $mrphase" && return 1
+ # fmtype defaults to siemens [only ncanda source has subj_fm_type - 20191111]
+ fmtype=$(subj_fm_type $id || echo siemens)
+ echo "$fmtype"
 
- preprocessDistortion -phasedir $mrphase -magdir $mrmag -fm_cfg $FM_CFG
+ case $fmtype in 
+     siemens)
+        echo "running siemens"
+       # find the t1dir with MRs in it
+       read mrmag mrphase < <(subj_fm $id)
+       [ -z "$mrmag" -o -z "$mrphase" ] && warn "could not find fm mag and phase for $id: source pipeline and source; 'subj_fm $id'" && return 1
+       [ ! -d "$mrmag" ] && warn "bad mrphase dir $mrmag" && return 1
+       [ ! -d "$mrphase" ] && warn "bad mrphase dir $mrphase" && return 1
+       preprocessDistortion -phasedir $mrphase -magdir $mrmag -fm_cfg $FM_CFG;;
+    *ge*rev)
+       read niidir < <(subj_fm $id)
+       [ -z "$niidir" ] && echo "no fm for $id" && return 1
+       preprocessDistortion -niidir $niidir -reverse -fm_cfg $FM_CFG;;
+    *ge|*ncanda*siemens)
+       read niidir < <(subj_fm $id)
+       [ -z "$niidir" ] && echo "no fm for $id" && return 1
+       preprocessDistortion -niidir $niidir -fm_cfg $FM_CFG;;
+   *)
+      echo "DONT KNOW WHAT TO DO WITH fieldmap type $fmtype" && return 1;;
+ esac
+ 
+
 
 
  # exit successfuly
diff --git a/sources/ncanda b/sources/ncanda
--- a/sources/ncanda
+++ b/sources/ncanda
@@ -6,22 +6,32 @@ SUBJECTS_DIR="/DNE/" # no freesurfer currently
 DICOM_PAT="*NONE" # no dicoms, comes from dataset
 
 FUNCTR="2.2" 
-FUNCSLICEACQ="??" # no slice acq have both GE and seiemns (interlaved)
+FUNCSLICEACQ="" # have both GE and seiemns (interlaved), see func below
 TEMPLATE_RES=MNI_3mm 
 SMOOTH_KERNEL=5
+TRUNC_VOLS=5
 
 MRROOT="/DNE/"
 NIIROOT="/Volumes/Hera/Raw/Datasets/NCANDA/"
 DBFILE="$NIIROOT/id_t1_epi.tsv"
+DBSITE="$NIIROOT/id_site.tsv"
 
 # TODO: make config for ncanda 
 FM_CFG=""
+_mkndcandasite(){
+   [ -r $DBSITE -a -z "$REDODBFILE" ] && return 0
+	perl -F, -slane 'next unless m/(baseline|followup_(\d+)y)/; $y=$2?$2:0; $F[0]=~s/NCANDA_//;print "$F[0]_$y\t$F[3]"'\
+      $NIIROOT/*/*REDCAP*/summaries/redcap/demographics.csv|
+      sort -u |tee $DBSITE
+}
 _mkncandadb() {
- # have 3 visits: find all that have both t1 and rest and
+ # have 5 visits: find all that have both t1 and rest and
  #  create session id like 'ncandaid_year' where baseline = year 0 to so 1y and 2y match raw directory names
  #  /Volumes/Hera/Raw/Datasets/NCANDA/baseline/NCANDA_IMAGEDATA_00012_V01/cases/NCANDA_S00095/standard/baseline/structural/native/t1.nii.gz
  #  /Volumes/Hera/Raw/Datasets/NCANDA/followup_1y/NCANDA_RELEASE_1Y_STRUCTURAL_IMAGES_V01/cases/NCANDA_S01009/standard/followup_1y/structural/native/t1.nii.gz
  [ -r $DBFILE -a -z "$REDODBFILE" ] && return 0
+ # break into id (baseline, followup_1y, followup_2y, ...) and full path to t1.nii.gz
+ # find resting state t2
  find $NIIROOT -name 't1.nii.gz' -path '*/structural/native/*' | 
   perl -MFile::Find -lne '
      if(m:NCANDA_(S\d+)/.*/(baseline|followup_\dy)/:){
@@ -60,6 +70,50 @@ function subj_t2 {
  [ -z "$t2" ] && echo "$FUNCNAME: no id $1" >&2 && return 1
  [ ! -r functional.nii.gz ] && 3dTcat -prefix functional.nii.gz -tr $FUNCTR ${t2/-001/*}
  [ -r functional.nii.gz ] && echo functional.nii.gz || return 1
+ return 0
+}
+
+subj_sliceacq() {
+ wantonlyoneid $@ || return 1
+ _mkndcandasite
+ echo interleaved
+ return 0
+ # determine baed on site
+ perl -lne '
+   BEGIN{ %site=("A"=>"interleaved","B"=>"GE", "C"=>"GE", "E"=>"GE",  "D"=>"interleaved"); }
+   if(/'"$1"'\t([A-Z])/) {
+      print $site{$1};
+      last}' $DBSITE 
+
+}
+
+subj_fm_type() {
+ wantonlyoneid $@ || return 1
+ _mkndcandasite
+ #  548 GE B
+ #  608 GE C
+ #  926 GE E
+ #  445 Siemens A
+ #  623 Siemens D
+ #    1 Siemens C
+ perl -lne 'BEGIN{ %site=("A"=>"ncanda siemens","B"=>"ncanda ge", "C"=>"ncanda ge rev", "E"=>"ncanda ge",  "D"=>"ncanda siemens"); }
+ if(/'"$1"'\t([A-Z])/) {print $site{$1}; last}' $DBSITE 
+}
+fm_cfg(){
+ wantonlyoneid $@ || return 1
+ subj_fm_type $1 | grep -q ge && echo "ncanda-ge" || echo "ncanda-siemens"
+ return 0
+}
+subj_fm(){
+ wantonlyoneid $@ || return 1
+ _mkndcandasite
+
+ local fmd=$(awk -v id="$1" '($1==id){print $3; quit}' $DBFILE)
+ [ -z "$fmd" ] && return 1
+ fmd=$(dirname ${fmd/rs-fMRI/fieldmap})
+ #/Volumes/Hera/Datasets/NCANDA/followup_4y/NCANDA_RELEASE_4Y_RESTINGSTATE_IMAGES_V01/cases/NCANDA_S00234/standard/followup_4y/restingstate/native/fieldmap
+ [ ! -d $fmd ] && warn "cannot find '$fmd'" && return 1
+ echo "$fmd"
  return 0
 }
 
