add rest_autocor

diff --git a/sources/PNC_rest b/sources/PNC_rest
--- a/sources/PNC_rest
+++ b/sources/PNC_rest
@@ -5,7 +5,7 @@ SOURCE_DESC80="PNC rest data"
 SUBJECTS_DIR="/Volumes/Phillips/Maria/PNC/Freesurfer/"
 DICOM_PAT="*.dcm"
 
-FUNCTR="3"
+FUNCTR="4"
 FUNCSLICEACQ="seqasc"
 
 MRROOT="/Volumes/Phillips/Maria/PNC/raw_data"
@@ -19,11 +19,31 @@ function subj_t1 {
  ## special cases for special subjects (rescans or other ambigiousness)
  # none yet
 
- # do not use original, use FS warped -- so we can use aseg
- #subj_mr_pat $MRROOT/$1 'axial_mprage_256x208*' 176 || return 1
+ # use finn's
+ file_exists_test /Volumes/Zeus/Finn/PNC/subjs/$1/struct/
 
- # FS T1
- file_exists_test "$SUBJECTS_DIR/$1/mri/T1.mgz"
+ # # return dicom dir
+ # # /Volumes/Phillips/Maria/PNC/raw_data/603155642406/T1_3DAXIAL/Dicoms/
+ # subj_mr_pat $MRROOT/$1/T1_3DAXIAL/ 'Dicoms' 160 || return 1
+
+ # previous annoted 
+ # do not use original, use FS warped -- so we can use aseg
+ # REVISED 20170424 WF
+ # #-- use what finn used -- which is NOT the freesurfer output
+ # # FS T1
+ # FST1="$SUBJECTS_DIR/$1/mri/T1.mgz"
+ # FST1gz="mprage.nii.gz"
+ # if [ ! -r "$FST1gz" ]; then
+ #  pwd >&2
+ #  if [ -r  "$FST1" ]; then
+ #   mri_convert "$FST1" "$FST1gz" 
+ #   wait
+ #  else
+ #   warn "cannot find $FST1 to convert"
+ #   return 1
+ #  fi
+ # fi
+ # file_exists_test "$FST1gz"
 }
 
 # segemention mask from freesurfer
@@ -34,22 +54,29 @@ function subj_FS_aseg {
 
 function subj_t2 {
  wantonlyoneid $@ || return 1
+ subj_mr_pat $MRROOT/$1/FMRI_BOLD_rest 'Dicoms' 124 || return 1
+}
+
+# was subj_t2 until 20170216 (WF) -- used by afni_wav+wm+gsr and nim_amy
+subj_t2_construct() {
+ wantonlyoneid $@ || return 1
  # would reconstruct from
-restdcmdir=$(subj_mr_pat $MRROOT/$1/FMRI_BOLD_rest 'Dicoms' 124) || return 1
-[ ! -d $DCMRECONDIR/$1 ] && mkdir -p $DCMRECONDIR/$1
-oldwd=$(pwd)
-cd $DCMRECONDIR/$1
+ restdcmdir=$(subj_t2 $1) || return 1
+
+ [ ! -d $DCMRECONDIR/$1 ] && mkdir -p $DCMRECONDIR/$1
+ oldwd=$(pwd)
+ cd $DCMRECONDIR/$1
 
  [ ! -r  "$DCMRECONDIR/$1/${1}_restepi+orig.HEAD" ] && 
-Dimon -infile_prefix $restdcmdir/ \
-        -GERT_Reco \
-        -dicom_org \
-        -sort_by_acq_time \
-        -gert_create_dataset \
-        -gert_to3d_prefix ${1}_restepi \
-        -quit
-cd $oldwd
-# use what we've already made
+ Dimon -infile_prefix $restdcmdir/ \
+         -GERT_Reco \
+         -dicom_org \
+         -sort_by_acq_time \
+         -gert_create_dataset \
+         -gert_to3d_prefix ${1}_restepi \
+         -quit
+ cd $oldwd
+ # use what we've already made
  file_exists_test "$DCMRECONDIR/$1/${1}_restepi+orig.HEAD"
 }
 
